abstract class SubscriptionInfoLookUpStates {}

class SubscriptionInfoLookUpInitialState extends SubscriptionInfoLookUpStates {}

class SubscriptionInfoLookUpLoadingState extends SubscriptionInfoLookUpStates {}

class SubscriptionInfoLookUpSuccessfullyState extends SubscriptionInfoLookUpStates {}

class SubscriptionInfoLookUpErrorState extends SubscriptionInfoLookUpStates {}